### ISSUE TITLE
Cannot filter Jenkins project to specific user view

### ISSUE THREAD

**Issue by chuck-g** [AdamNowotny/BuildReactor#1]
Many Jenkins projects have lots of builds that a particular user doesn't care about, so Jenkins has the concept of views, and these have some nice features like regex filtering to auto-include builds in the view. The BuildReactor plugin doesn't work when you give it the URL of a specific view, as it tries to append /all/cc.xml to the url. 

I'd like to see it auto-choose the projects in a view if a view is passed.

**Comment by dlubarov** [comment]
Automatically including new builds based on a regex would be really useful to us, since we regularly create new builds as part of our release workflow.

I could take a stab at implementing it. Does this mockup UI look about right?

<img width="590" alt="build-reactor-mockup" src="https://cloud.githubusercontent.com/assets/828366/10175853/25e6b3c4-66a6-11e5-9ff7-1067b00e76fe.png">

**Comment by AdamNowotny** [comment]
Currently the list of builds to monitor is determined only when you press save on settings screen. I presume that with patterns the expectation is that the list would be updated dynamically in the background whenever the build status is updated?

As I understand views are used in jenkins and configured by patterns as well. Wouldn't it be better if one could point to view instead of replicating the patterns in BuildReactor?

**Comment by dlubarov** [comment]
Yeah, that was my intention. We have some release branch builds on [Kochiku](https://kochiku.corp.squareup.com/android/register/master) (with CCTray integration) in addition to Jenkins, and Kochiku doesn't have a views feature.

I'm sure Jenkins view support would be useful to a lot of users, but wouldn't a more generic solution be best? Let me know what you think.

**Comment by AdamNowotny** [comment]
Yes, actually it makes sense. Being able to  monitor a view would be a different thing.
The ```jenkinsBuild.update()``` function would need to be modified to get the list of projects currently matching the patterns in addition to selected builds before fetching the status of each one.
Currently the configuration of monitored builds is stored in ```projects``` property for each service. Just add a new one to save the patterns (array of patterns?).
I'm working on a different feature but if you're willing to give it a go than let me know if some things need clarifying.

**Comment by AdamNowotny** [comment]
Jenkins integration has been rewritten in 1.0.0 and you can now enter a URL that points to a view.
