### ISSUE TITLE
BuildKite - Show pipelines is limited to 100

### ISSUE THREAD

**Issue by nurous** [AdamNowotny/BuildReactor#138]
It seems like the call to fetch the pipelines after clicking "Show" when configuring for BuildKite is paginated and therefore only shows the first 100 pipelines to be returned.

It would be great if it could list them all.

Current workaround:

1. Configure BuildKite for any of the pipelines returned
2. Go to "Configuration"
3. Click "Export"
4. Change the `projects` list to be the ones you need
5. Click "Save"

**Comment by AdamNowotny** [comment]
You can change the limit in https://github.com/AdamNowotny/BuildReactor/blob/master/src/services/buildkite/buildkiteRequests.js#L15
Not sure if removing it shows all builds 🤔

**Comment by nurous** [comment]
<img width="281" alt="Screenshot 2024-07-12 at 6 11 38 PM" src="https://github.com/user-attachments/assets/5ba6bd99-03ae-4618-bff2-7957780b5d3d">


Assuming it uses the GraphQL API `query OrganizationShowQuery` it would be good if the config would allow setting the options like; `pageSize`, `pipelineFilter`, `tagsFilter` and `teamSearch`, in order to allow control over the pipeline search.

**Comment by AdamNowotny** [comment]
BuildReactor uses the REST API, not GraphQL. I had a closer look and 100 is the maximum so we'd need to implement paging and get second page as well. https://buildkite.com/docs/apis/rest-api#pagination
I have just rewritten the BuildKite adapter (not published yet) so it just uses async/await promises instead of Rx - should be much simpler to modify now. The code getting pipelines is here https://github.com/AdamNowotny/BuildReactor/blob/master/src/services/buildkite/buildkite.ts#L21

**Comment by AdamNowotny** [comment]
In version 4.0.0 if there is a Link next HTTP header, the app will get more pages from BuildKite:
https://github.com/AdamNowotny/BuildReactor/blob/master/src/services/buildkite/buildkite.ts#L24-L27
Works locally, webstore publish still being reviewed by Google
