### ISSUE TITLE
[Jenkins] Notification shows only when job changes its status

### ISSUE THREAD

**Issue by dgorodnichy** [AdamNowotny/BuildReactor#14]
At this moment I see notification only when job changes its status. Is it possible to show notification after any job result?

**Comment by AdamNowotny** [comment]
That is by design as getting notifications for every change on an active project gets too noisy. I found it to be annoying in other notification tools. There are some cases where it might be useful though, like when the build contains my changes - I'd like to know about it even if state of the build did not change. Planning to implement it at some point, not high priority though.

**Comment by brandones** [comment]
+1

**Comment by AdamNowotny** [comment]
Version 1.0.0 adds "notifications" page where you can select "build started" and "build finished" to get notifications about all builds, not just the ones that changed status
