### ISSUE TITLE
Doesnt work with the Branches Plugin & the Folders Plugin

### ISSUE THREAD

**Issue by harshanandmv** [AdamNowotny/BuildReactor#25]
Doesnt work with the Branches Plugin & the Folders Plugin. 
Issue 1: Doesnt list the builds within a "feature" branch (or maybe because its within a folder, which is the 2nd issue)
Issue 2: Shows the build as disabled when the jenkins configs are within a folder.
![folders1](https://cloud.githubusercontent.com/assets/8823349/8502143/3f8d2ed0-21a4-11e5-9933-10238c2fa518.png)
![brancheswithfolder](https://cloud.githubusercontent.com/assets/8823349/8502166/872efcd2-21a4-11e5-9a92-f25669ecc014.png)

**Comment by AdamNowotny** [comment]
I see you're setting the url to point to specific views and jobs. Is this the same issue as https://github.com/AdamNowotny/BuildReactor/issues/1 ?

**Comment by nonspecialist** [comment]
Using the `github-folder` plugin and the `github-branch-source` plugin has this effect.

The (manual) workaround is to specify the base of the monitored build as `http[s]://jenkins-box/job/<orgfolder>/job/<reponame>` and then each branch is picked up automatically.

A potential fix for this would be:

* use `/api/json?tree=jobs[_class,name,url]` to find all "jobs" with `_class` of `jenkins.branch.OrganizationFolder`;
* for each organization represented by `$name` in the above, query `/job/$name/api/json?tree=jobs[_class,name,url]` for "jobs" with `_class` of `org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject`
* for each repository represented by `$name`s in _that_ set, use the `$url` to construct a set of "monitors", each of which will has all the branches that can be monitored

This isn't ideal, because with a large-ish set of monitored repositories, you end up with a potentially *huge* set of branches to display, and as repositories get added dynamically (when `Jenkinsfile`s are added, either by merge or PR) the set explodes further.

But at least we have a workaround

**Comment by AdamNowotny** [comment]
Thanks! Jenkins integration has rewritten in version 1.0.0 so that should work now. It is also possible to supply a URL to a view, not just the server.
