### ISSUE TITLE
69 projects from Jenkins and status timeout after 30 seconds, HTTP/1.1 200 OK in wireshark

### ISSUE THREAD

**Issue by christofferholmstedt** [AdamNowotny/BuildReactor#42]
I'm experiencing issues showing 69 projects from Jenkins in BuildReactor. It works when I start Chromium/Chrome with BuildReactor and the first 15 projects or so, are updated to their correct status. After that all other projects are in order switched to gray background with status "Offline (Connection timed out after 30 seconds) even though I've tried with 15, 60, 120 and 180 seconds update interval. When it is time for the first projects to be updated once again they also turn to "Offline" status. If I at this moment go in to settings and press the "show" button it also gives me timeout error (30 seconds). Are the 30 seconds timeout hardcoded somewhere?

It seems that requests are queued up and sent even though the timeout is way passed already so new requests end up in the bottom of some queue and not sent in due time. This is just a guess so I could be totally wrong here.

I'm trying to debug this to find the cause and when using Wireshark I still see a lot of API request from the BuildReactor plugin and responses from my Jenkins server are all HTTP/1.1 200 OK with application/json data, but BuildReactor shows them all as offline. I assume the responses I get are timestamped somehow and are too old for the BuildReactor plugin to show.

Any pointers on how I can move forward to debug this are appreciated.

**Comment by christofferholmstedt** [comment]
After some more testing it seems that the current max number of jobs is somewhere around 21 before they start to time out.

**Comment by christofferholmstedt** [comment]
Not sure if I should close this or not but I will for the time being.

I didn't know what to expect from Apache Tomcat/Jenkins in response time but I noticed that the requests from BuildReactor took much longer than the responses in Firefox. The root cause for this was the Active Directory connection from Jenkins timed out. The effect was that each HTTP round trip to Jenkins took about 4 seconds from BuildReactor. Temporarily using the built in user database in Jenkins gives a round trip time of about 0.2 seconds. No issues with BuildReactor with this configuration.

**Comment by AdamNowotny** [comment]
The interval only determines how long BR should wait before triggering another update. Timeout is a different thing and is not available in the UI. Currently it's pretty much hard-coded for most requests:
https://github.com/AdamNowotny/BuildReactor/blob/master/src/core/services/request.js#L15
The only request that is longer is Jenkins when getting list of available projects:
https://github.com/AdamNowotny/BuildReactor/blob/master/src/core/services/jenkins/buildService.js#L79

The problem is that all requests needed to update all projects are send at once, but the browser only actually sends a few of them with the rest waiting...but that does not affect the timeout.
For now I'll increase the number of seconds to 60, which should allow for more projects to be monitored, but what really needs to happen is BR should have some kind of queue for requests and send then in batches. Therefore I'll reopen the issue so I don't forget about it.

And yes, Jenkins API is pretty chatty to get all the information required...

**Comment by christofferholmstedt** [comment]
Yes, I was surprised to find out that Chrome/Chromium only opens 6 TCP connections to each server (15 or so for Firefox). It is for a good cause but not configurable so was a problem this time around. As you say a managed queue within BR sounds like the best solution...or perhaps enable HTTP/2 if possible and multiplex all requests. In theory it should work but support for HTTP/2 is sketchy at the moment.

**Comment by AdamNowotny** [comment]
Jenkins integration rewritten in version 1.0.0
