### ISSUE TITLE
Memory leak/crash, was: How to properly log/debug BuildReactor for non-reproducible bug?

### ISSUE THREAD

**Issue by christofferholmstedt** [AdamNowotny/BuildReactor#68]
Hi
I thought I asked this a year or so ago but can't find my earlier issue when I searched for it, so maybe I didn't.

I run BuildReactor in Chromium on a Raspberry Pi. From time to time the webpage (dashboard) doesn't load and I need to restart chromium to get it up and running again. This happens irregularly. After 1.0.0 release it has started to happen a bit more often so it is now worth trying to debug it properly. The interval between failures is somewhere between 12 and 48 hours.

Does Chromium or BuildReactor generate some crashlog if the plugin fails?
Can I start Chromium in some kind of special mode to get proper crashlog from when it happens?

**Comment by AdamNowotny** [comment]
You can see the logs in the background page, that's generally where the required info is.
There is currently no crashlog, just using "console" statements as saving a file would require a new permission.
I suspect however that the problem might be caused by a memory leak that I've seen crash the extension when lot of builds are monitored.
Can you check if memory consumption goes up significantly after a day? (shift-ESC in the browser).
Also what type of CI server are you using in BR and how many builds you monitor?

**Comment by christofferholmstedt** [comment]
Jenkins
70+ builds

Will start to properly monitor memory consumption.

**Comment by christofferholmstedt** [comment]
So I finally took the time to set up my environment to try to find the bug. With the Chromium Task Manager (shift+ESC) I could see that the memory leak is there somewhere. After a few hours the entire Raspberry Pi just froze and the BuildReactor plugin is now using 725 MB of memory.

How should I continue to debug this?

**Comment by christofferholmstedt** [comment]
After further testing the memory leak is persistent over several runs but the odd thing just occured during the last test. Instead of resulting in a completely frozen Raspberry Pi the BuildReactor plugin crashed and Chromium responded with the "Aw, Snap!" error page. After forcing a page reload of the dashboard BuildReactor started up as normal again.

Not sure if this is related or two different bugs. The only difference between the runs is that during the last run the display was turned off. Not sure if Raspbian has any HDMI status detection built in that could be interfering with the memory management but that is really a long-shot.

Any pointer for further debugging is appreciated.

**Comment by AdamNowotny** [comment]
From my limited investigation so far it looks like there is a leak when publishing new service status (either serviceUpdated or stateUpdated events). Perhaps some RxJS stream is saving old values instead of just the latest. So far I've only seen the extension crashing with "Aw snap!" page, reloading fixes it as it also reloads the background page and that's most likely when problems happen (after closing any other pages memory consumption stays high). Might be helpful to run Chrome devtools profiler on the background page to see what stays in memory.

It would be great to have some kind of http server with JSON responses running locally and then just point BR to it with update interval of 1 sec. Pretty sure that would make it much quicker to reproduce.

**Comment by christofferholmstedt** [comment]
> Might be helpful to run Chrome devtools profiler on the background page to see what stays in memory.

The devtools profiler, do you mean "Record Allocation Profile" or "Record Allocation Timeline" under the Memory tab?

I assume "the background page" is the dashboard, is this a correct?

I won't have time to debug it much more the upcoming month but will take another look at it in the end of August or so.

**Comment by AdamNowotny** [comment]
The dashboard page only connects to background page and receives messages from it.
The reason for it is that BuildReactor needs to work in the background event when popup/dashboard is not open so it can show the notifications when a build state changes.
More info at https://developer.chrome.com/extensions/background_pages
To open background page go to chrome://extensions/ and enable "developer mode" to see the pages.

Messages are exchanged using message passing (https://developer.chrome.com/extensions/messaging) defined in common/core.js in dashboard/popup and core/chromeListeners.js in the background page.

**Comment by christofferholmstedt** [comment]
Thanks for the information. I've had some time now to debug the background page and learnt some new things on the way (haven't done extension development before). For others here are some clarifactions and links:

@AdamNowotny writes above that you should open the background page and enable "Developer mode" to see the link to the background page. This page is a webpage generated internally by chrome/chromium for the purpose of being able to debug it. I tried a timeline recording first on google.com and though the background data would be recorded as well but of course that doesn't work. So make sure you:

1. Go to [chrome://extensions/](chrome://extensions/)
2. Enable "Developer Mode"
3. A link just below the the extension you want to debug is available to "Inspect views: Background page"

Here are some more links that may help:

- https://developers.google.com/web/tools/chrome-devtools/memory-problems/
- https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/timeline-tool#make-a-recording (deprecated in Chrome but Chromium still has these features)
- Stack Overflow answer/explanation of the background page: https://stackoverflow.com/a/18146702

# Back to the actual problem
The JS Heap is increasing and the number of listeners are increasing as well. The node count stays pretty low for the duration of the timeline recording 120 seconds. After only 120 seconds the listener count is around 500.

I begin the timeline recording with forcing a garbage collection ("Collect garbage" button) at 5 sec and finish the recording with another one. When I force garbage collection the listener count drops from 544 to 80. This is only after 120 seconds of recording. Node count has stayed the same throughout the recording, at 12.

Next step I assume is to figure out if the listener cound is actually supposed to go up, I assume not. After that is to track this back to actual JavaScript calls.

@AdamNowotny You meantioned earlier in this thread that it might be due to RxJS saving old values. Is this related to listeners count?

**Comment by AdamNowotny** [comment]
Thanks for the investigation. My first thought was that the RxJS sequences could be storing the whole sequence of build statuses instead of just the last one, but looks like it actually might be that some components are subscribing to sequences but not releasing them properly after use.
It seems that the leak happens faster if popup or dashboard are open to perhaps there is something about subscriptions in `core/messageHandlers.js`.
Other than that I'm planning to look at simplifying `core/services/serviceController.js` and `services/poolingService.js` once I move all services to new stateless API. My suspicion is that the way the events are handled there could contribute to problem. 2 more services to go...

**Comment by AdamNowotny** [comment]
Finally got some time to look at the problem. Turns out it's the logging, basically every update puts a log message in background page as well as the dashboard.
Expected Chrome to trim the log at some point but that does not seem to be happening, and fair enough - it's not common to put out that many messages to the log in that kind of application.
Try disabling the loggers and check if that helps. There are still some objects left behind, but either the profiler doesn't show anything or shows some system structures so not sure if anything more can be done. At least that should allow the dashboard to run for longer.
```
logger.init();
```
lines need to be commented out in [src/core/main.js](https://github.com/AdamNowotny/BuildReactor/tree/master/src/core/main.js) and [src/dashboard/main.js](https://github.com/AdamNowotny/BuildReactor/tree/master/src/dashboard/main.js)

**Comment by AdamNowotny** [comment]
Update: only looked at background page but actually there is another leak when dashboard is connected. I'll need to have a closer look. So disabling the logging only delays the crash, but it's not enough for a fix

**Comment by christofferholmstedt** [comment]
@AdamNowotny Thanks for looking into this. When you find a final fix don't hesitate to contact me for testing.

**Comment by rdavisunr** [comment]
@AdamNowotny - we are also seeing this behavior with 40+ builds from a Team City server. Chrome dies after ab out 8 hours. This is a great product and we are really looking forward to a fix.

**Comment by jleskovar-tyro** [comment]
Hey, any update on this? We're seeing this monitoring 30+ builds, across Jenkins and Buildkite. We're running this on Firefox 63, and we consistently see system memory usage grow to +90% after about 12 hours.

**Comment by AdamNowotny** [comment]
This is fixed in this commit https://github.com/AdamNowotny/BuildReactor/commit/8b9d839e11f53b7b7ab331d3ff7ead436fb09674
so if you get latest it should be fine. Sorry about the delay publishing to WebStore though, will update when it's done.

**Comment by rdavisunr** [comment]
@AdamNowotny - thanks! looking forward to the WebStore update...

**Comment by AdamNowotny** [comment]
2.0.0 has been published to WebStore. The problem was leaking subscriptions when more then one commit messages were preesent. Please reopen if still happening.
