### ISSUE TITLE
New feature: Add button to rebuild failed jobs

### ISSUE THREAD

**Issue by radarsh** [AdamNowotny/BuildReactor#84]
We use this plugin extensively in our organisation and everyone really appreciates the dashboard view. Quite often, there has been a desire to trigger another build on failed jobs. Would it be possible to add a control on the dashboard which can do this?

I appreciate that this might work differently for different build systems. We use Jenkins 2. Thanks a lot for the great plugin.

**Comment by AdamNowotny** [comment]
The focus of BuildReactor is to keep you informed about the build status only in a passive way (using notifications or the dashboard) so not planning on adding any "actions" unfortunately.
As you mentioned this would be different for each server as well so would make it a challenge to maintain.
You can however click on the broken build to open a tab with your CI server information for this specific build so that should be fairly quick to trigger.
If you really want that feature, your best bet would be to fork the project and implement it in a new dashboard copied from the existing one.
I would urge you however to spend the time to fix the flaky tests (or even disable them) instead so you can have repeatable builds you can trust.
